/* Generated by the Systemtap dtrace wrapper */


#define _SDT_HAS_SEMAPHORES 1


#define STAP_HAS_SEMAPHORES 1 /* deprecated */


#include <sys/sdt.h>

/* HELLOWORLD_INPUT_START ( ) */
#if defined STAP_SDT_V1
#define HELLOWORLD_INPUT_START_ENABLED() __builtin_expect (input_start_semaphore, 0)
#define helloworld_input_start_semaphore input_start_semaphore
#else
#define HELLOWORLD_INPUT_START_ENABLED() __builtin_expect (helloworld_input_start_semaphore, 0)
#endif
#define HELLOWORLD_INPUT_START() \
DTRACE_PROBE (helloworld, input_start)

