Vagrant.configure("2") do |config|
  config.vm.synced_folder '../../', '/vagrant', type: 'rsync'
  config.vm.box = "dipinhora/freebsd-11.1"
  config.vm.boot_timeout = 600
  config.vm.provider :libvirt do |libvirt|
    libvirt.driver = "qemu"
    libvirt.memory = 3072
    libvirt.cpus = 1
  end
end
