#
# Pull Request Tasks
#

task:
  only_if: $CIRRUS_PR != ''

  container:
    image: ponylang/ponyc-ci-x86-64-unknown-linux-gnu-builder:20200423
    cpu: 8
    memory: 24

  name: "PR: x86-64-unknown-linux-gnu"

  libs_cache:
    folder: build/libs
    fingerprint_script: echo "`md5sum lib/CMakeLists.txt` glibc 20200423"
    populate_script: make libs arch=x86-64 build_flags=-j8

  configure_script:
    - make configure arch=x86-64
  build_script:
    - make build arch=x86-64 build_flags=-j8
  test_script:
    - make test-ci arch=x86-64

task:
  only_if: $CIRRUS_PR != ''

  container:
    image: ponylang/ponyc-ci-x86-64-unknown-linux-gnu-builder:20200423
    cpu: 8
    memory: 24

  name: "PR: x86-64-unknown-linux-gnu [debug]"

  libs_cache:
    folder: build/libs
    fingerprint_script: echo "`md5sum lib/CMakeLists.txt` glibc 20200423"
    populate_script: make libs arch=x86-64 build_flags=-j8

  configure_script:
    - make configure arch=x86-64 config=debug
  build_script:
    - make build arch=x86-64 config=debug build_flags=-j8
  test_script:
    - make test-ci arch=x86-64 config=debug

task:
  only_if: $CIRRUS_PR != ''

  container:
    image: ponylang/ponyc-ci-x86-64-unknown-linux-musl-builder:20200421
    cpu: 8
    memory: 24

  name: "PR: x86-64-unknown-linux-musl"

  libs_cache:
    folder: build/libs
    fingerprint_script: echo "`md5sum lib/CMakeLists.txt` musl"
    populate_script: make libs arch=x86-64 build_flags=-j8

  configure_script:
    - make configure arch=x86-64
  build_script:
    - make build arch=x86-64 build_flags=-j8
  test_script:
    - make test-ci arch=x86-64

task:
  only_if: $CIRRUS_PR != ''

  freebsd_instance:
    image: freebsd-12-1-release-amd64
    cpu: 8
    memory: 24

  name: "PR: x86-64-unknown-freebsd-12.1"

  install_script:
    - echo "FETCH_RETRY = 6" >> /usr/local/etc/pkg.conf
    - echo "IGNORE_OSVERSION = yes" >> /usr/local/etc/pkg.conf
    - pkg update
    - pkg install -y cmake gmake libunwind git

  libs_cache:
    folder: build/libs
    fingerprint_script: echo "`md5 lib/CMakeLists.txt` freebsd-12.1"
    populate_script: gmake libs arch=x86-64 build_flags=-j8

  configure_script:
    - gmake configure arch=x86-64
  build_script:
    - gmake build arch=x86-64 build_flags=-j8
  test_script:
    - gmake test-ci arch=x86-64

task:
  only_if: $CIRRUS_PR != ''

  osx_instance:
    image: catalina-xcode-11.4.1

  name: "PR: x86-64-apple-darwin"

  install_script:
    - brew install coreutils

  libs_cache:
    folder: build/libs
    fingerprint_script: echo "`md5 lib/CMakeLists.txt` macos"
    populate_script: make libs arch=x86-64 build_flags=-j8

  configure_script:
    - make configure arch=x86-64
  build_script:
    - make build arch=x86-64 build_flags=-j8
  test_script:
    - make test-ci arch=x86-64

task:
  only_if: $CIRRUS_PR != ''

  windows_container:
    image: ponylang/ponyc-ci-x86-64-pc-windows-msvc-builder:20201208
    os_version: 2019
    cpu: 8
    memory: 24

  name: "PR: x86-64-pc-windows-msvc"

  libs_cache:
    folder: build/libs
    fingerprint_script:
      - ps: (Get-FileHash -Path lib\CMakeLists.txt).Hash
    populate_script:
      - ps: .\make.ps1 -Command libs -Generator "Visual Studio 16 2019"

  config_script:
    - ps: .\make.ps1 -Command configure -Config Release -Generator "Visual Studio 16 2019"
  build_script:
    - ps: .\make.ps1 -Command build -Config Release -Generator "Visual Studio 16 2019"
  test_script:
    - ps: .\make.ps1 -Command test -Config Release -Generator "Visual Studio 16 2019"

task:
  only_if: $CIRRUS_PR != ''

  windows_container:
    image: ponylang/ponyc-ci-x86-64-pc-windows-msvc-builder:20201208
    os_version: 2019
    cpu: 8
    memory: 24

  name: "PR: x86-64-pc-windows-msvc [debug]"

  timeout_in: 120m

  libs_cache:
    folder: build/libs
    fingerprint_script:
      - ps: (Get-FileHash -Path lib\CMakeLists.txt).Hash
    populate_script:
      - ps: .\make.ps1 -Command libs -Generator "Visual Studio 16 2019"

  config_script:
    - ps: .\make.ps1 -Command configure -Config Debug -Generator "Visual Studio 16 2019"
  build_script:
    - ps: .\make.ps1 -Command build -Config Debug -Generator "Visual Studio 16 2019"
  test_script:
    - ps: .\make.ps1 -Command test -Config Debug -Generator "Visual Studio 16 2019"


task:
  only_if: $CIRRUS_PR != ''

  container:
    image: ponylang/ponyc-ci-cross-arm:20200423
    cpu: 8
    memory: 24

  name: "PR: cross-compile: arm-unknown-linux-gnueabi"

  libs_cache:
    folder: build/libs
    fingerprint_script: echo "`md5sum lib/CMakeLists.txt` cross arm 20200423"
    populate_script: make libs build_flags=-j8 llvm_archs="X86;ARM"

  configure_script:
    - make configure
  build_script:
    - make build build_flags=-j8
  test_script:
    - make test-ci
  libponyrt_cross_script:
    - make cross-libponyrt CC=arm-linux-gnueabi-gcc CXX=arm-linux-gnueabi-g++ arch=armv7-a tune=cortex-a9 llc_arch=arm
  test_stdlib_cross_script:
    - make test-cross-ci PONYPATH=../armv7-a/release cross_triple=arm-unknown-linux-gnueabi cross_arch=armv7-a cross_cpu=cortex-a9 cross_linker=arm-linux-gnueabi-gcc cross_runner="qemu-arm-static -cpu cortex-a9 -L /usr/local/arm-linux-gnueabi/libc"

task:
  only_if: $CIRRUS_PR != ''

  container:
    image: ponylang/ponyc-ci-cross-armhf:20200423
    cpu: 8
    memory: 24

  name: "PR: cross-compile: arm-linux-gnueabihf-gcc"

  libs_cache:
    folder: build/libs
    fingerprint_script: echo "`md5sum lib/CMakeLists.txt` cross arm 20200423"
    populate_script: make libs build_flags=-j8 llvm_archs="X86;ARM"

  configure_script:
    - make configure
  build_script:
    - make build build_flags=-j8
  test_script:
    - make test-ci
  libponyrt_cross_script:
    - make cross-libponyrt CC=arm-linux-gnueabihf-gcc CXX=arm-linux-gnueabihf-g++ arch=armv7-a tune=cortex-a9 llc_arch=arm
  test_stdlib_cross_script:
    - make test-cross-ci PONYPATH=../armv7-a/release cross_triple=arm-unknown-linux-gnueabihf cross_arch=armv7-a cross_cpu=cortex-a9 cross_linker=arm-linux-gnueabihf-gcc cross_runner="qemu-arm-static -cpu cortex-a9 -L /usr/local/arm-linux-gnueabihf/libc"

#
# Nightly build tasks
#

task:
  only_if: $CIRRUS_CRON == "master-midnight"

  matrix:
    - name: "nightly: x86-64-unknown-linux-centos8"
      container:
        image: ponylang/ponyc-ci-x86-64-unknown-linux-centos8-builder:20200828
      environment:
        CACHE_BUSTER: 20200828
        TRIPLE_VENDOR: unknown
        TRIPLE_OS: linux-centos8
    - name: "nightly: x86-64-unknown-linux-gnu"
      container:
        image: ponylang/ponyc-ci-x86-64-unknown-linux-gnu-builder:20200423
      environment:
        CACHE_BUSTER: 20200423
        TRIPLE_VENDOR: unknown
        TRIPLE_OS: linux-gnu
    - name: "nightly: x86-64-unknown-linux-ubuntu18.04"
      container:
        image: ponylang/ponyc-ci-x86-64-unknown-linux-ubuntu18.04-builder:20200507
      environment:
        CACHE_BUSTER: 20200507
        TRIPLE_VENDOR: unknown
        TRIPLE_OS: linux-ubuntu18.04
    - name: "nightly: x86-64-unknown-linux-ubuntu20.04"
      container:
        image: ponylang/ponyc-ci-x86-64-unknown-linux-ubuntu20.04-builder:20200830
      environment:
        CACHE_BUSTER: 20200830
        TRIPLE_VENDOR: unknown
        TRIPLE_OS: linux-ubuntu20.04
    - name: "nightly: x86-64-unknown-linux-musl"
      container:
        image: ponylang/ponyc-ci-x86-64-unknown-linux-musl-builder:20200421
      environment:
        CACHE_BUSTER: 20200421
        TRIPLE_VENDOR: unknown
        TRIPLE_OS: linux-musl

  container:
    cpu: 8
    memory: 24

  environment:
    CLOUDSMITH_API_KEY: ENCRYPTED[!2cb1e71c189cabf043ac3a9030b3c7708f9c4c983c86d07372ae58ad246a07c54e40810d038d31c3cf3ed8888350caca!]

  libs_cache:
    folder: build/libs
    fingerprint_script:
      - echo "`md5sum lib/CMakeLists.txt`"
      - echo "${TRIPLE_VENDOR}-${TRIPLE_OS}"
      - echo "cache buster ${CACHE_BUSTER}"
    populate_script: make libs build_flags=-j8

  nightly_script:
    - bash .ci-scripts/x86-64-nightly.bash

task:
  only_if: $CIRRUS_CRON == "master-midnight"

  freebsd_instance:
    image: freebsd-12-1-release-amd64
    cpu: 8
    memory: 24

  name: "nightly: x86-64-unknown-freebsd-12.1"

  environment:
    CLOUDSMITH_API_KEY: ENCRYPTED[!2cb1e71c189cabf043ac3a9030b3c7708f9c4c983c86d07372ae58ad246a07c54e40810d038d31c3cf3ed8888350caca!]

  install_script:
    - echo "FETCH_RETRY = 6" >> /usr/local/etc/pkg.conf
    - echo "IGNORE_OSVERSION = yes" >> /usr/local/etc/pkg.conf
    - pkg update
    - pkg install -y bash cmake gmake libunwind git py37-pip
    - pip install --upgrade cloudsmith-cli

  libs_cache:
    folder: build/libs
    fingerprint_script: echo "`md5 lib/CMakeLists.txt` freebsd-12.1"
    populate_script: gmake libs arch=x86-64 build_flags=-j8

  nightly_script:
    - bash .ci-scripts/x86-64-unknown-freebsd-12.1-nightly.bash

task:
  only_if: $CIRRUS_CRON == "master-midnight"

  osx_instance:
    image: catalina-xcode-11.4.1

  name: "nightly: x86-64-apple-darwin"

  environment:
    TRIPLE_VENDOR: apple
    TRIPLE_OS: darwin
    CLOUDSMITH_API_KEY: ENCRYPTED[!2cb1e71c189cabf043ac3a9030b3c7708f9c4c983c86d07372ae58ad246a07c54e40810d038d31c3cf3ed8888350caca!]

  libs_cache:
    folder: build/libs
    fingerprint_script: echo "`md5 lib/CMakeLists.txt` macos"
    populate_script: make libs build_flags=-j8

  install_script:
    - brew install coreutils python
    - pip3 install --upgrade cloudsmith-cli

  nightly_script:
    - export TZ=utc
    - bash .ci-scripts/x86-64-nightly.bash

task:
  only_if: $CIRRUS_CRON == "master-midnight"

  windows_container:
    image: ponylang/ponyc-ci-x86-64-pc-windows-msvc-builder:20201208
    os_version: 2019
    cpu: 8
    memory: 24

  name: "nightly: x86-64-pc-windows-msvc"

  environment:
    CLOUDSMITH_API_KEY: ENCRYPTED[!2cb1e71c189cabf043ac3a9030b3c7708f9c4c983c86d07372ae58ad246a07c54e40810d038d31c3cf3ed8888350caca!]

  libs_cache:
    folder: build/libs
    fingerprint_script:
      - ps: (Get-FileHash -Path lib\CMakeLists.txt).Hash
    populate_script:
      - ps: .\make.ps1 -Command libs -Generator "Visual Studio 16 2019"

  config_script:
    - ps: .\make.ps1 -Command configure -Config Release -Generator "Visual Studio 16 2019" -Prefix "build\install\release" -Version nightly
  build_script:
    - ps: .\make.ps1 -Command build -Config Release -Generator "Visual Studio 16 2019" -Prefix "build\install\release" -Version nightly
  install_script:
    - ps: .\make.ps1 -Command install -Config Release -Prefix "build\install\release"
  package_script:
    - ps: .\make.ps1 -Command package -Config Release -Prefix "build\install\release" -Version nightly
  upload_script:
    - ps: $version = (Get-Date).ToString("yyyyMMdd"); cloudsmith push raw --version $version --api-key $env:CLOUDSMITH_API_KEY --summary "Pony compiler" --description "https://github.com/ponylang/ponyc" ponylang/nightlies build\ponyc-x86-64-pc-windows-msvc.zip

#
# Release build tasks
#

task:
  only_if: $CIRRUS_TAG =~ '^\d+\.\d+\.\d+$'

  matrix:
    - name: "release: x86-64-unknown-linux-centos8"
      container:
        image: ponylang/ponyc-ci-x86-64-unknown-linux-centos8-builder:20200828
      environment:
        CACHE_BUSTER: 20200828
        TRIPLE_VENDOR: unknown
        TRIPLE_OS: linux-centos8
    - name: "release: x86-64-unknown-linux-gnu"
      container:
        image: ponylang/ponyc-ci-x86-64-unknown-linux-gnu-builder:20200423
      environment:
        CACHE_BUSTER: 20200423
        TRIPLE_VENDOR: unknown
        TRIPLE_OS: linux-gnu
    - name: "release: x86-64-unknown-linux-ubuntu18.04"
      container:
        image: ponylang/ponyc-ci-x86-64-unknown-linux-ubuntu18.04-builder:20200507
      environment:
        CACHE_BUSTER: 20200507
        TRIPLE_VENDOR: unknown
        TRIPLE_OS: linux-ubuntu18.04
    - name: "release: x86-64-unknown-linux-ubuntu20.04"
      container:
        image: ponylang/ponyc-ci-x86-64-unknown-linux-ubuntu20.04-builder:20200830
      environment:
        CACHE_BUSTER: 20200830
        TRIPLE_VENDOR: unknown
        TRIPLE_OS: linux-ubuntu20.04
    - name: "release: x86-64-unknown-linux-musl"
      container:
        image: ponylang/ponyc-ci-x86-64-unknown-linux-musl-builder:20200421
      environment:
        CACHE_BUSTER: 20200421
        TRIPLE_VENDOR: unknown
        TRIPLE_OS: linux-musl

  container:
    cpu: 8
    memory: 24

  environment:
    CLOUDSMITH_API_KEY: ENCRYPTED[!2cb1e71c189cabf043ac3a9030b3c7708f9c4c983c86d07372ae58ad246a07c54e40810d038d31c3cf3ed8888350caca!]

  libs_cache:
    folder: build/libs
    fingerprint_script:
      - echo "`md5sum lib/CMakeLists.txt`"
      - echo "${TRIPLE_VENDOR}-${TRIPLE_OS}"
      - echo "cache buster ${CACHE_BUSTER}"
    populate_script: make libs build_flags=-j8

  release_script:
    - bash .ci-scripts/x86-64-release.bash

task:
  only_if: $CIRRUS_TAG =~ '^\d+\.\d+\.\d+$'

  freebsd_instance:
    image: freebsd-12-1-release-amd64
    cpu: 8
    memory: 24

  name: "release: x86-64-unknown-freebsd-12.1"

  environment:
    CLOUDSMITH_API_KEY: ENCRYPTED[!2cb1e71c189cabf043ac3a9030b3c7708f9c4c983c86d07372ae58ad246a07c54e40810d038d31c3cf3ed8888350caca!]

  install_script:
    - echo "FETCH_RETRY = 6" >> /usr/local/etc/pkg.conf
    - echo "IGNORE_OSVERSION = yes" >> /usr/local/etc/pkg.conf
    - pkg update
    - pkg install -y bash cmake gmake libunwind git py37-pip
    - pip install --upgrade cloudsmith-cli

  libs_cache:
    folder: build/libs
    fingerprint_script: echo "`md5 lib/CMakeLists.txt` freebsd-12.1"
    populate_script: gmake libs arch=x86-64 build_flags=-j8

  release_script:
    - bash .ci-scripts/x86-64-unknown-freebsd-12.1-release.bash

task:
  only_if: $CIRRUS_TAG =~ '^\d+\.\d+\.\d+$'

  osx_instance:
    image: catalina-xcode-11.4.1

  name: "release: x86-64-apple-darwin"

  environment:
    TRIPLE_VENDOR: apple
    TRIPLE_OS: darwin
    CLOUDSMITH_API_KEY: ENCRYPTED[!2cb1e71c189cabf043ac3a9030b3c7708f9c4c983c86d07372ae58ad246a07c54e40810d038d31c3cf3ed8888350caca!]

  libs_cache:
    folder: build/libs
    fingerprint_script: echo "`md5 lib/CMakeLists.txt` macos"
    populate_script: make libs build_flags=-j8

  install_script:
    - brew install coreutils python
    - pip3 install --upgrade cloudsmith-cli

  release_script:
    - bash .ci-scripts/x86-64-release.bash

task:
  only_if: $CIRRUS_TAG =~ '^\d+\.\d+\.\d+$'

  windows_container:
    image: ponylang/ponyc-ci-x86-64-pc-windows-msvc-builder:20201208
    os_version: 2019
    cpu: 8
    memory: 24

  name: "release: x86-64-pc-windows-msvc"

  environment:
    CLOUDSMITH_API_KEY: ENCRYPTED[!2cb1e71c189cabf043ac3a9030b3c7708f9c4c983c86d07372ae58ad246a07c54e40810d038d31c3cf3ed8888350caca!]

  libs_cache:
    folder: build/libs
    fingerprint_script:
      - ps: (Get-FileHash -Path lib\CMakeLists.txt).Hash
    populate_script:
      - ps: .\make.ps1 -Command libs -Generator "Visual Studio 16 2019"

  config_script:
    - ps: .\make.ps1 -Command configure -Config Release -Generator "Visual Studio 16 2019" -Prefix "build\install\release" -Version (Get-Content .\VERSION)
  build_script:
    - ps: .\make.ps1 -Command build -Config Release -Generator "Visual Studio 16 2019" -Prefix "build\install\release" -Version (Get-Content .\VERSION)
  install_script:
    - ps: .\make.ps1 -Command install -Config Release -Prefix "build\install\release"
  package_script:
    - ps: .\make.ps1 -Command package -Config Release -Prefix "build\install\release" -Version (Get-Content .\VERSION)
  upload_script:
    - ps: $version = (Get-Content .\VERSION); cloudsmith push raw --version $version --api-key $env:CLOUDSMITH_API_KEY --summary "Pony compiler" --description "https://github.com/ponylang/ponyc" ponylang/releases build\ponyc-x86-64-pc-windows-msvc.zip
