#
# Nightly build tasks
#

task:
  only_if: $CIRRUS_API_CREATED == "true"

  container:
    image: ponylang/ponyc-ci-x86-64-unknown-linux-gnu-builder:20191105
    cpu: 8
    memory: 24

  name: "nightly: x86-64-unknown-linux-gnu"

  environment:
    CLOUDSMITH_API_KEY: ENCRYPTED[!2cb1e71c189cabf043ac3a9030b3c7708f9c4c983c86d07372ae58ad246a07c54e40810d038d31c3cf3ed8888350caca!]

  nightly_script:
    - bash .ci-scripts/x86-64-unknown-linux-gnu-nightly.bash ${CLOUDSMITH_API_KEY}


task:
  only_if: $CIRRUS_API_CREATED == "true"

  container:
    image: ponylang/ponyc-ci-x86-64-unknown-linux-musl-builder:20191105
    cpu: 8
    memory: 24

  name: "nightly: x86-64-unknown-linux-musl"

  environment:
    CLOUDSMITH_API_KEY: ENCRYPTED[!2cb1e71c189cabf043ac3a9030b3c7708f9c4c983c86d07372ae58ad246a07c54e40810d038d31c3cf3ed8888350caca!]

  nightly_script:
    - bash .ci-scripts/x86-64-unknown-linux-musl-nightly.bash ${CLOUDSMITH_API_KEY}

#
# Release build tasks
#

task:
  only_if: $CIRRUS_TAG =~ '^\d+\.\d+\.\d+$'

  container:
    image: ponylang/ponyc-ci-x86-64-unknown-linux-gnu-builder:20191105
    cpu: 8
    memory: 24

  name: "release: x86-64-unknown-linux-gnu"

  environment:
    CLOUDSMITH_API_KEY: ENCRYPTED[!2cb1e71c189cabf043ac3a9030b3c7708f9c4c983c86d07372ae58ad246a07c54e40810d038d31c3cf3ed8888350caca!]

  release_script:
    - bash .ci-scripts/x86-64-unknown-linux-gnu-release.bash ${CLOUDSMITH_API_KEY}

task:
  only_if: $CIRRUS_TAG =~ '^\d+\.\d+\.\d+$'

  container:
    image: ponylang/ponyc-ci-x86-64-unknown-linux-musl-builder:20191105
    cpu: 8
    memory: 24

  name: "release: x86-64-unknown-linux-musl"

  environment:
    CLOUDSMITH_API_KEY: ENCRYPTED[!2cb1e71c189cabf043ac3a9030b3c7708f9c4c983c86d07372ae58ad246a07c54e40810d038d31c3cf3ed8888350caca!]

  release_script:
    - bash .ci-scripts/x86-64-unknown-linux-musl-release.bash ${CLOUDSMITH_API_KEY}

#
# Pull Request Tasks
#

task:
  only_if: $CIRRUS_BRANCH != 'master' && $CIRRUS_BRANCH != 'release' && $CIRRUS_API_CREATED != "true"

  container:
    image: ponylang/ponyc-ci-x86-64-unknown-linux-gnu-builder:20191105
    cpu: 8
    memory: 24

  name: "PR: x86-64-unknown-linux-gnu"

  test_script:
    - make -f Makefile-lib-llvm default_pic=true arch=x86-64 config=release -j8
    - make -f Makefile-lib-llvm default_pic=true arch=x86-64 config=release test-ci

task:
  only_if: $CIRRUS_BRANCH != 'master' && $CIRRUS_BRANCH != 'release' && $CIRRUS_API_CREATED != "true"

  container:
    image: ponylang/ponyc-ci-x86-64-unknown-linux-musl-builder:20191105
    cpu: 8
    memory: 24

  name: "PR: x86-64-unknown-linux-musl"

  test_script:
    - make -f Makefile-lib-llvm default_pic=true arch=x86-64 config=release link=static -j8
    - make -f Makefile-lib-llvm default_pic=true arch=x86-64 config=release link=static test-ci

task:
  only_if: $CIRRUS_BRANCH != 'master' && $CIRRUS_BRANCH != 'release' && $CIRRUS_API_CREATED != "true"

  freebsd_instance:
    image: freebsd-12-0-release-amd64
    cpu: 8
    memory: 24

  name: "PR: x86-64-unknown-freebsd12.0"

  install_script:
    - echo "FETCH_RETRY = 6" >> /usr/local/etc/pkg.conf
    - pkg update
    - pkg install -y cmake gmake libunwind git

  test_script:
    - gmake -f Makefile-lib-llvm default_pic=true arch=x86-64 config=release -j8
    - gmake -f Makefile-lib-llvm default_pic=true arch=x86-64 config=release test-ci

task:
  only_if: $CIRRUS_BRANCH != 'master' && $CIRRUS_BRANCH != 'release' && $CIRRUS_API_CREATED != "true"

  osx_instance:
    image: mojave-xcode-11.2.1

  name: "PR: macOS"

  install_script:
    - brew install coreutils

  test_script:
    - export CC1=clang
    - export CXX1=clang++
    - make -f Makefile-lib-llvm default_pic=true arch=x86-64 config=release -j8
    - make -f Makefile-lib-llvm default_pic=true arch=x86-64 config=release test-ci
