use "pony_test"
use "pony_check"
use notifier = "notifier"

actor \nodoc\ Main is TestList
  new create(env: Env) =>
    PonyTest(env, this)

  new make() =>
    None

  fun tag tests(test: PonyTest) =>
    notifier.Main.make().tests(test)
    test(_TestCanListen)
    test(_TestListenerLocalAddress)
    test(_TestMute)
    test(_TestOutgoingFails)
    test(_TestPingPong)
    test(_TestSSLPingPong)
    test(_TestSSLLargePayload)
    test(_TestBasicBufferUntil)
    test(_TestUnmute)
    test(_TestFakeMuteFullBuffer)
    test(_TestSSLMute)
    test(_TestSSLMuteCloseDropsHeld)
    test(_TestSendToken)
    test(_TestSendAfterClose)
    test(_TestSendAcceptedBeforeSent)
    test(_TestSendCloseFromAccepted)
    test(_TestSendCloseFromSent)
    test(_TestSendHardCloseFromAccepted)
    test(_TestSendHardCloseFromSentKeepsDelivered)
    test(_TestSendOnSentPrecedesReceived)
    test(_TestSendReentrantFromSent)
    test(_TestMuteFromOnSent)
    test(_TestHardCloseDuringReceive)
    test(_TestHardCloseAfterFramedReceive)
    test(_TestSSLHardCloseDuringReceive)
    test(_TestSSLCloseDuringReceive)
    test(_TestSSLHardCloseOnConnected)
    test(_TestSSLHardCloseOnStarted)
    test(_TestStartTLSHardCloseOnTLSReady)
    test(_TestStartTLSPingPong)
    test(_TestStartTLSPreconditions)
    test(_TestHardCloseWhileConnecting)
    test(_TestCloseWhileConnecting)
    test(_TestSendv)
    test(_TestSendvEmpty)
    test(_TestSendvMixedEmpty)
    test(_TestSSLSendv)
    test(_TestSendSSLLargeSingleSend)
    test(_TestIdleTimeout)
    test(_TestIdleTimeoutReset)
    test(_TestIdleTimeoutDisable)
    test(_TestIdleTimeoutRearms)
    test(_TestIdleTimeoutRearmsDuringTLSUpgrade)
    test(_TestSSLIdleTimeout)
    test(_TestSSLIdleTimeoutNotArmedDuringHandshake)
    test(_TestSSLIdleTimeoutDeferredArm)
    test(_TestYieldRead)
    test(_TestSSLYieldRead)
    test(_TestIP4PingPong)
    test(_TestIP6PingPong)
    test(_TestMaxSpawnRejectsZero)
    test(_TestMaxSpawnAcceptsBoundary)
    test(_TestDefaultMaxSpawn)
    test(_TestReadBufferSizeRejectsZero)
    test(_TestReadBufferSizeAcceptsBoundary)
    test(_TestDefaultReadBufferSize)
    test(_TestReadBufferConstructorSize)
    test(_TestSetReadBufferMinimumSuccess)
    test(_TestSetReadBufferMinimumBelowBufferSize)
    test(_TestResizeReadBufferSuccess)
    test(_TestResizeReadBufferBelowBufferSize)
    test(_TestResizeReadBufferBelowMinLowersMin)
    test(_TestBufferSizeAboveMinimum)
    test(_TestBufferSizeAtMinimum)
    test(_TestSocketOptionsConnected)
    test(_TestSocketOptionsNotConnected)
    test(_TestConnectionTimeoutFires)
    test(_TestConnectionTimeoutCancelledOnConnect)
    test(_TestSSLConnectionTimeoutFires)
    test(_TestSSLConnectionTimeoutCancelledOnConnect)
    test(_TestConnectionTimeoutValidationRejectsZero)
    test(_TestConnectionTimeoutValidationAcceptsBoundary)
    test(_TestCloseWhileConnectingWithTimeout)
    test(_TestHardCloseWhileConnectingWithTimeout)
    test(_TestTimerFires)
    test(_TestTimerCancel)
    test(_TestTimerNotResetByIO)
    test(_TestSetTimerNotOpen)
    test(_TestSetTimerAlreadyActive)
    test(_TestTimerRearmFromCallback)
    test(_TestTimerCancelWrongToken)
    test(_TestTimerHardCloseCleanup)
    test(_TestTimerSetDuringClosing)
    test(_TestTimerDurationValidationRejectsZero)
    test(_TestTimerDurationValidationAcceptsBoundary)
    test(_TestFakeTimerSurvivesClose)
    test(_TestSetTimerNotOpenDuringSSLHandshake)
    test(_TestSetTimerNotOpenDuringSSLHandshakeServer)
    test(_TestSSLHandshakeFailureClient)
    test(_TestSSLHandshakeFailureServer)
    test(_TestSSLHandshakeCompleteTransitionsToOpen)
    test(_TestSSLIsWriteableDuringHandshake)
    test(_TestSSLSendDuringHandshake)
    test(_TestSSLCloseDuringHandshake)
    test(_TestSSLHardCloseDuringHandshake)
    test(_TestSSLServerHardCloseDuringHandshake)
    test(_TestStartTLSSendDuringUpgrade)
    test(_TestStartTLSIsWriteableDuringUpgrade)
    test(_TestStartTLSHandshakeFailure)
    test(_TestStartTLSAuthFailure)
    test(_TestSetTimerAfterTLSUpgrade)
    // POSIX only: these provoke write backpressure with a fixed payload, which
    // Windows loopback won't trigger (it buffers far beyond SO_SNDBUF/RCVBUF).
    // The drain and write-only re-arm logic they cover is platform-neutral.

    // UDP tests
    test(_TestUDPBindFailure)
    test(_TestUDPFakeSendOk)
    test(_TestUDPFakeSendWouldBlock)
    test(_TestUDPFakeSendError)
    test(_TestUDPFakeSendNotOpen)
    test(_TestUDPFakeRecvData)
    test(_TestUDPFakeCloseFromReceived)
    test(_TestUDPFakeRecvError)
    test(_TestUDPFakeYieldReading)
    test(_TestUDPFakeBudget)
    test(_TestUDPDisposeInitRace)
    test(_TestUDPSocketState)
    test(_TestUDPEcho)

    // DNS / NetAddress tests (no sockets)
    test(_TestDNSBroadcastIP4)
    test(_TestDNSBroadcastIP6)
    test(_TestNetAddressNameRoundTripIP4)
    test(_TestNetAddressNameRoundTripIP6)
    test(_TestNetAddressIP6Scope)
    test(_TestDNSUnresolvableEmpty)

    // UDP read-buffer edge cases (real sockets)
    test(_TestUDPOversizedDatagramTruncated)
    test(_TestUDPUndersizedDatagramDelivered)
    test(_TestUDPEmptyDatagramDelivered)
    test(_TestUDPSmallReadBufferTruncates)

    // Broadcast tests (real sockets)
    ifdef not osx then test(_TestBroadcast) end
    ifdef linux then test(_TestBroadcastReceive) end

    // Multicast tests (real sockets)
    ifdef (not osx) and (not bsd) then test(_TestMulticastSockopt) end
    test(_TestMulticastIP4)
    test(_TestMulticastIP6)

    // Fake-backend tests (no real sockets for I/O)
    test(_TestFakeSendOk)
    test(_TestFakeSendMultipleTokenOrder)
    test(_TestFakeSendOnClosed)
    test(_TestFakeSendError)
    test(_TestFakeSendFailedAfterClosed)
    test(_TestFakeRecvError)
    test(_TestFakeRecvRetry)
    test(_TestFakeRecvData)
    test(_TestFakeRecvFramed)
    test(_TestFakeMute)
    test(_TestFakeYieldReading)
    test(_TestFakeGracefulClose)
    test(_TestFakeConnectDNSFailure)
    test(_TestFakeConnectInflight)
    test(_TestFakeSendWhileConnecting)
    test(_TestFakeSendWhileUnconnectedClosing)
    test(_TestFakeHardCloseDuringUnconnectedClosing)
    test(_TestFakeListenFailure)
    test(_TestFakeAccept)
    test(_TestFakeConnectionLimit)
    ifdef posix then test(_TestStaleForeignEventDropped) end
    ifdef posix then test(_TestBackpressureDrain) end
    ifdef posix then test(_TestWriteOnlyEventReadRecovery) end
    ifdef posix then test(_TestSendPerTokenCompletion) end
    ifdef posix then test(_TestSendMidFlightDropBoundary) end
    ifdef posix then test(_TestSendSSLPerTokenCompletion) end
    ifdef posix then test(_TestSendSSLMidFlightDropBoundary) end
    ifdef posix then test(_TestSendGracefulCloseWithPending) end
    ifdef posix then test(_TestSendSSLGracefulCloseWithPending) end
    ifdef posix then test(_TestSendCloseFromThrottled) end
    ifdef posix then test(_TestSendHardCloseFromThrottled) end
    ifdef posix then test(_TestSendSSLHardCloseFromThrottled) end
    ifdef posix then test(_TestSendDeliveredNotFailedOnHardClose) end
    ifdef posix then test(_TestReadableEventWriteRecovery) end
    ifdef posix then test(_TestSendOnSentPrecedesThrottleAndClose) end
    ifdef posix then test(_TestSendThrottleSuppressedByHardClose) end

    // SSL/DTLS session tests (transport-independent)
    test(_TestALPNProtocolListEncoding)
    test(_TestALPNProtocolListDecode)
    test(_TestALPNProtocolListOffsetOf)
    test(Property1UnitTest[Array[String]](
      _TestALPNProtocolListOffsetOfRoundtrip))
    test(_TestALPNStandardProtocolResolver)
    test(_TestSSLHandshakeInMemory)
    test(_TestSSLCreateClientNoAvailableProtocol)
    test(_TestSSLReceiveNonTLSBytes)
    test(_TestSSLReceiveUntrustedChain)
    test(_TestSSLReceivePeerRejectedOurCert)
    test(_TestSSLReceiveHostnameMismatch)
    test(_TestSSLReceiveNoSharedVersion)
    test(_TestSSLReceiveNoPeerCertificate)
    test(_TestSSLReceiveVerifyOffNeverAuthFails)
    test(_TestSSLReceiveUnprovenCertificate)
    test(_TestSSLReceiveUntrustedClientChain)
    test(_TestSSLReceiveALPNFatalWithQueuedError)
    test(_TestERRCodeFields)
    test(_TestSSLFailedHandshakeDoesNotAffectLaterRead)
    test(_TestSSLReadReportsGenuineError)
    test(_TestSSLReadAfterErrorReturnsOnlyDecryptedBytes)
    test(_TestSSLReadWithBufferedBytes)
    test(_TestSSLReadNoExpectAfterError)
    test(_TestSSLReadPendingExceedsExpect)
    test(_TestSSLReadOnAuthFail)
    test(_TestSSLALPNSelectedOnAuthFail)
    test(_TestSSLALPNSelectedOnError)
    test(_TestSSLReceiveOnAuthFail)
    test(_TestSSLReceiveOnError)
    test(_TestSSLCloseFromReady)
    test(_TestSSLCloseIdempotent)
    test(_TestSSLCloseFromWrongStates)
    test(_TestSSLCloseAfterDispose)
    test(_TestSSLPeerCloseNotifyDetected)
    test(_TestSSLBufferedDataDrainedOnCloseNotify)
    test(_TestSSLReceiveInClosed)
    test(_TestSSLWriteBlockedInClosed)
    test(_TestSSLBidirectionalCloseRoundtrip)
    test(_TestSSLCorruptRecordInClosed)
    test(_TestSSLSendOnFailedSession)
    test(_TestSSLWriteBlockedInClosing)
    test(_TestSSLDisposeBeforeHandshake)
    test(_TestSSLDisposeTwice)
    test(_TestSSLReadAfterDispose)
    test(_TestSSLReadAfterDisposeWithBufferedFrame)
    test(_TestSSLReceiveAfterDispose)
    test(_TestSSLSendAfterDisposeReturnsNone)
    test(_TestSSLWriteAfterDispose)
    test(_TestSSLALPNSelectedAfterDispose)
    test(_TestSSLContextDisposeTwice)
    test(_TestSSLContextALPNSetResolverAfterDispose)
    test(_TestSSLContextALPNFallbackToClientProtocol)
    test(_TestSSLContextALPNUnadvertisedProtocolFails)
    test(_TestSSLContextALPNResolverRootedByContext)
    test(_TestSSLContextALPNResolverRootedBySession)
    test(_TestSSLContextALPNResolverUnreferenced)
    test(_TestSSLContextALPNSetClientProtocolsAfterDispose)
    test(_TestSSLContextSetMinProtoVersionInvertedRange)
    test(_TestSSLContextSetMaxProtoVersionInvertedRange)
    test(_TestSSLContextSetMinProtoVersionAfterDispose)
    test(_TestSSLContextSetMaxProtoVersionAfterDispose)
    test(_TestSSLContextGetMinProtoVersionAfterDispose)
    test(_TestSSLContextGetMaxProtoVersionAfterDispose)
    test(_TestSSLContextGetMinProtoVersionOnValReceiver)
    test(_TestSSLContextGetMaxProtoVersionOnValReceiver)
    test(_TestSSLContextSetAuthorityRootCertsAfterDispose)
    test(_TestSSLContextSetAuthorityAfterDispose)
    test(_TestSSLContextSetCertAfterDispose)
    test(_TestSSLContextSetCiphersAfterDispose)
    test(_TestSSLContextSetVerifyDepthAfterDispose)
    test(_TestSSLContextAllowTLSAfterDispose)
    test(_TestSSLContextAllowTLSV1u2)
    test(_TestSSLContextClientAfterDispose)
    test(_TestSSLContextServerAfterDispose)
    test(_TestDTLSHandshakeInMemory)
    test(_TestDTLSReceiveUntrustedChain)
    test(_TestDTLSReceiveVerifyOffNeverAuthFails)
    test(_TestDTLSReceiveHostnameMismatch)
    test(_TestDTLSDisposeBeforeHandshake)
    test(_TestDTLSDisposeTwice)
    test(_TestDTLSReadAfterDispose)
    test(_TestDTLSReceiveAfterDispose)
    test(_TestDTLSContextDisposeTwice)
    test(_TestDTLSContextClientAfterDispose)
    test(_TestDTLSContextServerAfterDispose)
    test(_TestDTLSContextSetMinProtoVersionAfterDispose)
    test(_TestDTLSContextSetMaxProtoVersionAfterDispose)
    test(_TestDTLSContextSetAuthorityAfterDispose)
    test(_TestDTLSContextSetCertAfterDispose)
    test(_TestDTLSContextSetCiphersAfterDispose)
    test(_TestDTLSContextSetVerifyDepthAfterDispose)
    test(_TestDTLSContextALPNSetResolverAfterDispose)
    test(_TestDTLSContextALPNSetClientProtocolsAfterDispose)
    test(_TestDTLSWriteAfterDispose)
    test(_TestDTLSSendAfterDisposeReturnsNone)
    test(_TestDTLSReadAfterDisposeWithBufferedFrame)
    test(_TestDTLSReadOnAuthFail)
    test(_TestDTLSReceiveOnAuthFail)
    test(_TestDTLSSendOnFailedSession)
    test(_TestDTLSCloseFromReady)
    test(_TestDTLSCloseIdempotent)
    test(_TestDTLSCloseFromWrongStates)
    test(_TestDTLSCloseAfterDispose)
    test(_TestDTLSPeerCloseNotifyDetected)
    test(_TestDTLSWriteBlockedInClosed)
    test(_TestDTLSBidirectionalCloseRoundtrip)
    test(_TestDTLSWriteBlockedInClosing)
    test(Property1UnitTest[Array[String]](_TestALPNProtocolListRoundTrip))
    test(_TestMatchNameEmptyName)
    test(_TestMatchNameExactCaseInsensitive)
    test(_TestMatchNameNoMatch)
    test(_TestMatchNameIPLiteral)
    test(_TestMatchNameWildcard)
    test(_TestMatchNameWildcardInsufficientLevels)
