name: Add discuss during sync label

on:
  issues:
    types:
      - opened
      - reopened
  issue_comment:
    types:
      - created
  pull_request_target:
    types:
      - opened
      - edited
      - ready_for_review
      - reopened
  pull_request_review:
    types:
      - submitted

permissions:
  pull-requests: write

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Add "discuss during sync" label to active GH entity
        uses: andymckay/labeler@467347716a3bdbca7f277cb6cd5fa9c5205c5412
        with:
          repo-token: ${{ secrets.PONYLANG_MAIN_API_TOKEN }}
          add-labels: "discuss during sync"
