name: Lint GitHub Action Workflows

on: pull_request

concurrency:
  group: lint-actions-${{ github.ref }}
  cancel-in-progress: true

permissions:
  packages: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Check workflow files
        uses: docker://ghcr.io/ponylang/shared-docker-ci-actionlint:20250119
        with:
          args: -color
