name: pony-compiler

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - 'src/libponyc/**'
      - 'tools/lib/ponylang/pony_compiler/**'
      - '.github/workflows/pr-pony-compiler.yml'

concurrency:
  group: pr-pony-compiler-${{ github.ref }}
  cancel-in-progress: true

permissions:
  packages: read

jobs:
  linux:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    name: Linux
    container:
      image: ghcr.io/ponylang/ponyc-ci-alpine3.23-builder:20260201
      options: --user pony
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Build libs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LIBS_IMAGE: ghcr.io/ponylang/ponyc-ci-alpine3.23-builder:20260201
          LIBS_TAG: ${{ hashFiles('Makefile', 'CMakeLists.txt', 'lib/CMakeLists.txt', 'lib/llvm/patches/*') }}
        run: make libs-ci llvm_tools=false build_flags=-j4 libs_cache_image="$LIBS_IMAGE" libs_cache_tag="$LIBS_TAG"
      - name: Build
        run: |
          make configure config=debug
          make build config=debug
      - name: Test pony-compiler
        run: make test-pony-compiler config=debug

  macos:
    if: github.event.pull_request.draft == false
    runs-on: macos-26

    name: macOS
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Build libs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LIBS_TAG: ${{ hashFiles('Makefile', 'CMakeLists.txt', 'lib/CMakeLists.txt', 'lib/llvm/patches/*') }}
        run: make libs-ci llvm_tools=false build_flags=-j3 libs_cache_package=arm64-macos-26 libs_cache_tag="$LIBS_TAG"
      - name: Build
        run: |
          make configure arch=armv8 config=debug
          make build config=debug
      - name: Test pony-compiler
        run: make test-pony-compiler config=debug

  windows:
    if: github.event.pull_request.draft == false
    runs-on: windows-2025-vs2026
    defaults:
      run:
        shell: pwsh

    name: Windows
    steps:
      - name: Disable Windows Defender
        run: Set-MpPreference -DisableRealtimeMonitoring $true
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Build libs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LIBS_TAG: ${{ hashFiles('make.ps1', 'CMakeLists.txt', 'lib/CMakeLists.txt', 'lib/llvm/patches/*') }}
        run: .\make.ps1 -Command libs-ci -LlvmTools false -LibsCachePackage windows-2025-vs2026 -LibsCacheTag $env:LIBS_TAG
      - name: Build
        run: |
          .\make.ps1 -Command configure -Config Debug
          .\make.ps1 -Command build -Config Debug
      - name: Test pony-compiler
        run: .\make.ps1 -Command test -Config Debug -TestsToRun pony-compiler-tests
