name: Tools

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - '**'
      - '!**/*.md'
      - '!**/*.yml'
      - '!.dockerfiles/**'
      - '!.ci-dockerfiles/**'
      - '.github/workflows/pr-tools.yml'

concurrency:
  group: pr-tools-${{ github.ref }}
  cancel-in-progress: true

permissions:
  packages: read

jobs:
  tools:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    name: Tools
    container:
      image: ghcr.io/ponylang/ponyc-ci-alpine3.23-builder:20260201
      options: --user pony
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Restore Libs Cache
        id: restore-libs
        uses: actions/cache/restore@v4
        with:
          path: |
            build/libs
            lib/llvm/src/compiler-rt/lib/builtins
          key: libs-ghcr.io/ponylang/ponyc-ci-alpine3.23-builder:20260201-${{ hashFiles('Makefile', 'CMakeLists.txt', 'lib/CMakeLists.txt', 'lib/llvm/patches/*') }}
      - name: Build Libs
        if: steps.restore-libs.outputs.cache-hit != 'true'
        run: make libs build_flags=-j8
      - name: Build
        run: |
          make configure config=debug
          make build config=debug
      - name: Test pony-doc
        run: make test-pony-doc config=debug
      - name: Test pony-lint
        run: make test-pony-lint config=debug
      - name: Test pony-lsp
        run: make test-pony-lsp config=debug
      - name: Lint pony-lint
        run: make lint-pony-lint config=debug
