name: Tools

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - '**'
      - '!**/*.md'
      - '!**/*.yml'
      - '!.dockerfiles/**'
      - '!.ci-dockerfiles/**'
      - '.github/workflows/pr-tools.yml'

concurrency:
  group: pr-tools-${{ github.ref }}
  cancel-in-progress: true

permissions:
  packages: read

jobs:
  linux:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    name: Linux
    container:
      image: ghcr.io/ponylang/ponyc-ci-alpine3.23-builder:20260201
      options: --user pony
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Restore Libs Cache
        id: restore-libs
        uses: actions/cache/restore@v5.0.3
        with:
          path: |
            build/libs
            lib/llvm/src/compiler-rt/lib/builtins
          key: libs-ghcr.io/ponylang/ponyc-ci-alpine3.23-builder:20260201-${{ hashFiles('Makefile', 'CMakeLists.txt', 'lib/CMakeLists.txt', 'lib/llvm/patches/*') }}
      - name: Build Libs
        if: steps.restore-libs.outputs.cache-hit != 'true'
        run: make libs build_flags=-j8
      - name: Build
        run: |
          make configure config=debug
          make build config=debug
      - name: Test pony-doc
        run: make test-pony-doc config=debug
      - name: Test pony-lint
        run: make test-pony-lint config=debug
      - name: Test pony-lsp
        run: make test-pony-lsp config=debug
      - name: Lint pony-lint
        run: make lint-pony-lint config=debug
      - name: Lint pony-doc
        run: make lint-pony-doc config=debug
      - name: Lint pony-lsp
        run: make lint-pony-lsp config=debug

  macos:
    if: github.event.pull_request.draft == false
    runs-on: macos-26

    name: macOS
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Restore Libs Cache
        id: restore-libs
        uses: actions/cache/restore@v5.0.3
        with:
          path: |
            build/libs
            lib/llvm/src/compiler-rt/lib/builtins
          key: libs-arm64-macos-26-${{ hashFiles('Makefile', 'CMakeLists.txt', 'lib/CMakeLists.txt', 'lib/llvm/patches/*') }}
      - name: Build Libs
        if: steps.restore-libs.outputs.cache-hit != 'true'
        run: make libs build_flags=-j4
      - name: Build
        run: |
          make configure arch=armv8 config=debug
          make build config=debug
      - name: Test pony-doc
        run: make test-pony-doc config=debug
      - name: Test pony-lint
        run: make test-pony-lint config=debug
      - name: Test pony-lsp
        run: make test-pony-lsp config=debug

  windows:
    if: github.event.pull_request.draft == false
    runs-on: windows-2025
    defaults:
      run:
        shell: pwsh

    name: Windows
    steps:
      - name: Disable Windows Defender
        run: Set-MpPreference -DisableRealtimeMonitoring $true
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Restore Libs Cache
        id: restore-libs
        uses: actions/cache/restore@v5.0.3
        with:
          path: |
            build/libs
            lib/llvm/src/compiler-rt/lib/builtins
          key: libs-windows-2025-${{ hashFiles('make.ps1', 'CMakeLists.txt', 'lib/CMakeLists.txt', 'lib/llvm/patches/*') }}
      - name: Build Libs
        if: steps.restore-libs.outputs.cache-hit != 'true'
        run: .\make.ps1 -Command libs
      - name: Build
        run: |
          .\make.ps1 -Command configure -Config Debug
          .\make.ps1 -Command build -Config Debug
      - name: Test pony-doc
        run: .\make.ps1 -Command test -Config Debug -TestsToRun pony-doc-tests
      - name: Test pony-lint
        run: .\make.ps1 -Command test -Config Debug -TestsToRun pony-lint-tests
      - name: Test pony-lsp
        run: .\make.ps1 -Command test -Config Debug -TestsToRun pony-lsp-tests
