use "pony_test"
use dep = ".."

actor \nodoc\ Main is TestList
  new create(env: Env) => PonyTest(env, this)
  new make() => None

  fun tag tests(test: PonyTest) =>
    // PathValidator tests
    test(_TestPathValidatorSimplePath)
    test(_TestPathValidatorNestedPath)
    test(_TestPathValidatorEmptyPath)
    test(_TestPathValidatorAbsolutePath)
    test(_TestPathValidatorDotDot)
    test(_TestPathValidatorDot)
    test(_TestPathValidatorBackslash)
    test(_TestPathValidatorNulByte)
    test(_TestPathValidatorConsecutiveSlashes)
    test(_TestPathValidatorTrailingSlash)
    test(_TestPathValidatorDriveLetter)
    test(_TestPathValidatorDotDotSubstring)

    // ArchiveEncoder tests
    test(_TestArchiveEncoderSingleFile)
    test(_TestArchiveEncoderDirectory)
    test(_TestArchiveEncoderNestedDirectories)
    test(_TestArchiveEncoderEmptyDirectory)
    test(_TestArchiveEncoderSkipsSymlinks)
    test(_TestArchiveEncoderDeterministicOrder)
    test(_TestArchiveEncoderRootDirectory)
    test(_TestArchiveEncoderUnreadableFile)

    // Sha256 tests
    test(_TestSha256Empty)
    test(_TestSha256Abc)
    test(_TestSha256TwoBlocks)
    test(_TestSha256OneBlock)
    test(_TestSha256LongMessage)
    test(_TestSha256Hex)

    // ContentHash tests
    test(_TestContentHashSingleFile)
    test(_TestContentHashTwoFiles)
    test(_TestContentHashThreeFiles)
    test(_TestContentHashFourFiles)
    test(_TestContentHashFiveFiles)
    test(_TestContentHashPathBinding)
    test(_TestContentHashEmpty)
    test(_TestContentHashEmptyContent)
    test(_TestContentHashNestedDirs)
    test(_TestContentHashSkipsSymlinks)

    // ArchiveDecoder tests
    test(_TestArchiveDecoderRoundTrip)
    test(_TestArchiveDecoderRoundTripNested)
    test(_TestArchiveDecoderEmptyDirectory)
    test(_TestArchiveDecoderRoundTripEmptyFile)
    test(_TestArchiveDecoderRejectsTruncatedArchive)
    test(_TestArchiveDecoderErrorsOnMkdirFailure)
    test(_TestArchiveDecoderErrorsOnMissingArchive)
    test(_TestArchiveDecoderRejectsPathTraversal)
    test(_TestArchiveDecoderRejectsUnknownVersion)
    test(_TestArchiveDecoderRejectsUnknownType)
    test(_TestArchiveDecoderRejectsAbsolutePath)
    test(_TestArchiveDecoderFromBytesSingleFile)
    test(_TestArchiveDecoderFromBytesNested)
    test(_TestArchiveDecoderFromBytesInvalid)

    // Pack tests
    test(_TestPackRoundTrip)
    test(_TestPackHash)
    test(_TestPackEmptyDirectory)
    test(_TestPackSourceNotFound)
    test(_TestPackSourceIsFile)
    test(_TestPackOutputInsideSource)

    // FetchAll tests
    test(_TestFetchAllBadDepType)
    test(_TestFetchAllConfigParseError)
    test(_TestFetchAllConfigNotFound)
    test(_TestFetchAllSkipsPresent)
    test(_TestFetchAllSkipsPresentUppercaseHex)
    test(_TestFetchAllEmptyDeps)
    test(_TestFetchAllOutputNotDirectory)

    // ConfigParser tests
    test(_TestConfigParserMinimalValid)
    test(_TestConfigParserSingleDep)
    test(_TestConfigParserDocUrl)
    test(_TestConfigParserMultipleDeps)
    test(_TestConfigParserVersionTab)
    test(_TestConfigParserComments)
    test(_TestConfigParserHashSkip)
    test(_TestConfigParserUnknownFields)
    test(_TestConfigParserNoTrailingNewline)
    test(_TestConfigParserHashUppercaseHex)
    test(_TestConfigParserEmptyFile)
    test(_TestConfigParserMissingVersion)
    test(_TestConfigParserContentBeforeVersion)
    test(_TestConfigParserUnsupportedVersion)
    test(_TestConfigParserVersionZero)
    test(_TestConfigParserInvalidVersionNumber)
    test(_TestConfigParserMissingEnd)
    test(_TestConfigParserMissingRequiredField)
    test(_TestConfigParserMissingType)
    test(_TestConfigParserMissingUrl)
    test(_TestConfigParserMissingRef)
    test(_TestConfigParserDuplicateField)
    test(_TestConfigParserDuplicateDepName)
    test(_TestConfigParserNestedDep)
    test(_TestConfigParserEmptyDepName)
    test(_TestConfigParserDepNameWithSpaces)
    test(_TestConfigParserDepNameWithTabs)
    test(_TestConfigParserEndTrailingContent)
    test(_TestConfigParserOrphanEnd)
    test(_TestConfigParserUnexpectedTopLevel)
    test(_TestConfigParserDuplicateVersion)
    test(_TestConfigParserInvalidHashFormat)
    test(_TestConfigParserHashWrongLength)
    test(_TestConfigParserHashBadHex)
    test(_TestConfigParserFieldMissingValue)
    test(_TestConfigParserDepNoName)
    test(_TestConfigParserDepNameSlash)
    test(_TestConfigParserDepNameBackslash)
    test(_TestConfigParserDepNameDotDot)
    test(_TestConfigParserDepNameDot)
